language: csharp
git:
  depth: 9999
matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    before_deploy: 
      - git config --local user.name "Open Identity Platform Community" && git config --local user.email "open-identity-platform-openam@googlegroups.com"
      - git checkout -f $TRAVIS_BRANCH
      - git tag -f $git_version
      - xbuild /p:Configuration=Release ru.org.openam.dotnet.sln
      - cp ru.org.openam.iis.httpmodule/Properties/AssemblyInfo.cs ru.org.openam.iis.httpmodule/bin/Release/ru.org.openam.version.txt
      - cat ru.org.openam.iis.httpmodule/bin/Release/ru.org.openam.version.txt
      - zip -rjv  /tmp/ru.org.openam.iis.httpmodule.zip ru.org.openam.iis.httpmodule/bin/Release/* 
      - git push --quiet --force https://$GITHUBKEY@github.com/$TRAVIS_REPO_SLUG.git $git_version >/dev/null 2>&1
    deploy:
      provider: releases
      draft: false
      prerelease: false
      target_commitish: $(git rev-list -n 1 $git_version)
      tag_name: $git_version
      name: $git_version
      body: "compare: $(git rev-list -n 1 $git_version_last)...$(git rev-list -n 1 $git_version)"
      api_key:
        secure: WZqOaX/rVO2iub470iv+t9L9Ii5rIjrnYWIleJ5SuvGekGdgpqI0xL2AIKjsRl/1ygX2nEnWPy1V9clz1K3hAiLwyG5Nq9iXWyIkc7XOiUB58UHie95d/bvx50tCVXjovNfgTN+5gr0mhAQ5aDZ1CHnJUKIdsQ8HP0zZ1YPjqXsJlwWr7fwKQrmZINC0WjN8pYyZV+5tzA/e8YNv5OAf2rHa5JGOXDOPjZ8HXC92tdfEStr6QzugQ970VrzsesO59C6bJKgpuNauXKLoZKpZ++MMtUX1vsLeFU2E5Iz/OmBURGQ70RWWITarqEiLgH1h5p6KP1RoJyxEtwsmbPYeGMjvQfH8oVywBU4wJkk6+wC7U0sq9nNUaUr/+YO1Vyn67hpB//AYKzFWKEjXQL4RjxhWf1i0VDtNogiqdW7x88gPujqo9YDkySzCy5JvUAzEUioSosOboHKKbyXgguEfAf/+GqiH7fzZLQzt2TjMy3ysRoxbTg8MmcTFgB/508xoc88oA7ikZSwA4xe03FuYke94opM37XvUppg+4qMM+TGY8pB/fzI6jHijjCN4mCB8eaITbRzRSnbdOGMErBgxaP2EyIkglVY9E58/YnMWxyjTgFyfpy+HhL8yZKZI61I60HhL8ISQQ0qtG1VSBZe5SA8DaHWv+ljQ4L4kKb199tg=
      skip_cleanup: true
      overwrite: true
      file_glob: true
      file: 
        - "/tmp/ru.org.openam.iis.httpmodule.zip"
      on:
        repo: OpenIdentityPlatform/OpenAM-.Net-Agent
        tags: false
        branch: 
          - master
          - travis
    after_deploy:
      - echo 'after_deploy'
  - os: osx
before_install:
 - date -u
 - uname -a
 - export PATH=/opt/mono/bin:$PATH
 - # if [[ "$TRAVIS_OS_NAME" == "osx" ]] ; then brew install rpm wine; else sudo apt-get install -y rpm wine; fi
 - git fetch -t
 - export git_version_last="$(git describe --abbrev=0 --tags --always)"
 - export git_version="$(echo $git_version_last | awk -F . '{ printf "%d.%d.%d", $1,$2,$3 + 1}')"
 - env | sort
 - git log `git describe --tags --abbrev=0 HEAD^ --always`..HEAD --oneline
solution: ru.org.openam.dotnet.sln
branches:
  except:
    - /[0-9]+\.[0-9]+\.[0-9]+$/
notifications:
 email:
  - open-identity-platform-openam@googlegroups.com
install:
  - nuget restore ru.org.openam.dotnet.sln
  - nuget install NUnit.Runners -Version 3.8.0 -OutputDirectory testrunner
script:
  - git fetch -t
  - xbuild /p:Configuration=Debug ru.org.openam.dotnet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./ru.org.openam.nunit/bin/Debug/ru.org.openam.sdk.nunit.dll
