language: csharp
os:
 - osx
 - linux
git:
  depth: 9999
before_install:
 - date -u
 - uname -a
 - export PATH=/opt/mono/bin:$PATH
 - env | sort
solution: ru.org.openam.dotnet.sln
branches:
 only:
   - master
notifications:
 email:
  - open-identity-platform-openam@googlegroups.com
install:
  - nuget restore ru.org.openam.dotnet.sln
  - nuget install NUnit.Runners -Version 3.6.0 -OutputDirectory testrunner
script:
  - git fetch -t
  - xbuild /p:Configuration=Release ru.org.openam.dotnet.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.6.0/tools/nunit3-console.exe ./ru.org.openam.nunit/bin/Release/ru.org.openam.sdk.nunit.dll
