version: '{build}'
build:
  project: ru.org.openam.dotnet.sln
  verbosity: minimal
platform:
  - Any CPU
configuration:
  - Release
notifications:
  - provider: Email
    to:
      - open-identity-platform-openam@googlegroups.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
init:
  - ps: Update-AppveyorBuild -Version "$env:appveyor_build_number: $($env:appveyor_repo_commit.substring(0,7))"
before_build:
  - cmd: nuget restore
after_build:
 - ps: type ru.org.openam.iis.httpmodule\Properties\AssemblyInfo.cs
 - ps: copy ru.org.openam.iis.httpmodule\Properties\AssemblyInfo.cs ru.org.openam.iis.httpmodule\bin\Release\ru.org.openam.version.txt
 - ps: cd ru.org.openam.iis.httpmodule\bin\Release
 - ps: 7z a ru.org.openam.iis.httpmodule.zip *
 - ps: Push-AppveyorArtifact ru.org.openam.iis.httpmodule.zip
